SELECT ROW_NUMBER() OVER () AS ID
,C.NAME AS CONCEPTO_NAME
,C.ID AS CONCEPTO_ID
,T.OBRA_ID
,O.NAME AS OBRA_NAME
,T.SUBCONTRATISTA_ID
,S.LAST_NAME || ', ' || S.FIRST_NAME AS SUBCONTRATISTA
,SUM(T.COST) AS COST
FROM TAREA T
INNER JOIN OBRA O ON T.OBRA_ID = O.ID
INNER JOIN SUBCONTRATISTA S ON T.SUBCONTRATISTA_ID = S.ID
INNER JOIN CONCEPTO C ON T.CONCEPTO_ID = C.ID
GROUP BY C.NAME
,C.ID
,T.OBRA_ID
,T.SUBCONTRATISTA_ID
