 SELECT ROW_NUMBER() OVER () AS ID
      , M.SUBCONTRATISTA_ID
	  , S.LAST_NAME || ', ' || S.FIRST_NAME AS SUBCONTRATISTA
	  , M.OBRA_ID, O.NAME AS OBRA_NAME 
FROM MOVIMIENTO M 
LEFT OUTER JOIN SUBCONTRATISTA S ON S.ID = M.SUBCONTRATISTA_ID 
LEFT OUTER JOIN OBRA O ON O.ID = M.OBRA_ID 
WHERE (SUBCONTRATISTA_ID IS NOT NULL) OR (OBRA_ID IS NOT NULL)