SELECT ROW_NUMBER() OVER () AS ID
,T.OBRA_ID
,O.NAME AS OBRA_NAME
,T.SUBCONTRATISTA_ID
,S.LAST_NAME || ', ' || S.FIRST_NAME AS SUBCONTRATISTA
FROM TAREA T
INNER JOIN OBRA O ON T.OBRA_ID = O.ID
INNER JOIN SUBCONTRATISTA S ON T.SUBCONTRATISTA_ID = S.ID
GROUP BY T.OBRA_ID
,T.SUBCONTRATISTA_ID
order by t.obra_id,t.subcontratista_id