 SELECT ROW_NUMBER() OVER (ORDER BY O.NAME) AS "ID"
      , O.NAME AS "OBRA"
      , O.ID AS "OBRA_ID"
      , S.LAST_NAME || ', ' || S.FIRST_NAME AS "SUBCONTRATISTA"
	  , S.ID AS "SUBCONTRATISTA_ID"
	  , C.NAME AS "CONCEPTO"
	  , C.ID AS "CONCEPTO_ID"
	  , SUM(T.COST) AS "TOTAL_COST"
  FROM TAREA T
  INNER JOIN OBRA O ON T.OBRA_ID = O.ID
  INNER JOIN SUBCONTRATISTA S ON T.SUBCONTRATISTA_ID = S.ID
  INNER JOIN CONCEPTO C ON T.CONCEPTO_ID = C.ID
  GROUP BY O.NAME
      , O.ID
      , S.LAST_NAME || ', ' || S.FIRST_NAME
	  , S.ID
	  , C.NAME
	  , C.ID;
